const state={filter:"すべて",query:"",onlyUnlearned:false,done:new Set(JSON.parse(localStorage.getItem("fe-done")||"[]"))};
const fields=["すべて",...new Set(QUESTIONS.map(x=>x.field))];
const $=s=>document.querySelector(s);
const esc=s=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));

const box=(text,cls="")=>`<div class="v-box ${cls}">${text}</div>`;
const arrow=(label="")=>`<div class="v-arrow"><i>→</i>${label?`<small>${label}</small>`:""}</div>`;
const flow=(parts)=>`<div class="v-flow">${parts.map((x,i)=>`${i?arrow():""}${box(esc(x),i===parts.length-1?"focus":"")}`).join("")}</div>`;
const compare=(leftTitle,left,rightTitle,right)=>`<div class="v-compare"><section><h4>${leftTitle}</h4>${left.map(x=>`<p>${x}</p>`).join("")}</section><b>VS</b><section class="good"><h4>${rightTitle}</h4>${right.map(x=>`<p>${x}</p>`).join("")}</section></div>`;
const formula=(top,bottom)=>`<div class="v-formula"><strong>${top}</strong><span>${bottom}</span></div>`;
const stack=(layers)=>`<div class="v-stack">${layers.map((x,i)=>`<div style="--i:${i}">${x}</div>`).join("")}</div>`;
const cycle=(items)=>`<div class="v-cycle">${items.map((x,i)=>`<div><b>${i+1}</b><span>${x}</span></div>`).join("")}</div>`;
const network=(center,nodes)=>`<div class="v-network">${box(center,"hub")}${nodes.map((x,i)=>`<div class="sat s${i+1}">${x}</div>`).join("")}</div>`;
function richVisual(q){
  switch(q.n){
    case 1:return `<div class="precision"><div><small>小さい値</small><i style="width:7%"></i><i style="width:11%"></i><b>先に加算</b></div><div><small>大きい値</small><i class="huge"></i><b>最後に加算</b></div></div>`;
    case 2:return `<div class="markov-calc"><div class="markov-route"><span>雨</span><i></i><b>晴</b><i></i><strong>晴</strong></div><div class="markov-route"><span>雨</span><i></i><b>曇</b><i></i><strong>晴</strong></div><div class="markov-route"><span>雨</span><i></i><b>雨</b><i></i><strong>晴</strong></div><div class="markov-rule">各経路は「掛ける」<em>×</em>　経路同士は「足す」<em>＋</em></div></div>`;
    case 3:return stack(["目的タスク：分類・要約・専門応答","特定データによる追加学習","汎用の事前学習済みLLM"]);
    case 4:return `<div class="wave"><svg viewBox="0 0 500 180" role="img"><path d="M5 90 C45 10 85 10 125 90 S205 170 245 90 S325 10 365 90 S445 170 495 90"/><g>${[20,70,120,170,220,270,320,370,420,470].map((x,i)=>`<circle cx="${x}" cy="${90-65*Math.sin((x-5)/120*Math.PI)}" r="6"/><line x1="${x}" y1="165" x2="${x}" y2="${90-65*Math.sin((x-5)/120*Math.PI)}"/>`).join("")}</g></svg><div>連続波形 <b>→ 標本化 →</b> 離散値</div></div>`;
    case 5:return `<div class="tree"><b>8</b><div><span>4</span><span>12</span></div><div><i>2</i><i>6</i><i>10</i><i>14</i></div><small>各部分木の中央値が根になる</small></div>`;
    case 6:return `<div class="dfs-tree"><div class="dfs-level root"><b>0</b></div><div class="dfs-level"><span>1</span><span>左部分木を完走</span><span>右へ</span></div><div class="dfs-level leaves"><i>2</i><i>3</i><i>…</i><i class="target">対象の葉<br><strong>11番目</strong></i><i>…</i></div><small>行きがけ順：ノードへ到着した瞬間に番号を付ける</small></div>`;
    case 7:return compare("オーバーライド",["継承先で再定義","同じシグネチャ"],"オーバーロード",["同じメソッド名","引数の型・個数が違う"]);
    case 8:return formula("MIPS = 1 ÷ 命令実行時間(秒) ÷ 10⁶","nsなら 10³ ÷ 平均命令時間(ns)");
    case 9:return `<div class="timer-ring"><div>0</div><span>開始値</span><i>65536<br>カウント</i><span>終了値</span><b>1周して差を測る</b></div>`;
    case 10:return `<div class="stripe"><div><b>A1</b><b>A4</b></div><div><b>A2</b><b>A5</b></div><div><b>A3</b><b>A6</b></div><span>3台へ分散し並列I/O</span></div>`;
    case 11:return compare("フェールソフト",["機能を縮退","運転を継続"],"フェールセーフ",["異常を検知","安全側へ停止・制動"]);
    case 12:return `<div class="capacity">${box("Web<br>1 CPU → 2 CPU")}${arrow("20件/秒")}${box("DB<br>2 CPU → 4 CPU","focus")}<strong>追加 1 + 2 = 3 CPU</strong></div>`;
    case 13:return `<div class="bits"><div style="flex:20">仮想ページ番号<strong>20 bit</strong></div><div style="flex:12">ページ内変位<strong>12 bit</strong></div><small>4KB = 2¹² byte</small></div>`;
    case 14:return compare("ノーコード",["GUIだけ","コード原則なし"],"ローコード",["GUI中心","必要部分はコード"]);
    case 15:return flow(["GPLを改変","第三者へ配布","同条件＋ソース提供"]);
    case 16:return `<div class="seven-seg"><div class="binary"><span>0x92</span><b>1001 0010</b><small>アノードコモン：0の線が点灯</small></div><div class="seg-display"><i class="a"></i><i class="b"></i><i class="c"></i><i class="d"></i><i class="e"></i><i class="f"></i><i class="g"></i><em>配線表へ対応させる</em></div></div>`;
    case 17:return `<div class="ears"><span>🔊</span><div>左右の時間差<br>音量差・耳の特性</div><b>👤</b><em>後方から聞こえる感覚</em></div>`;
    case 18:return network("人物A",["人物B","商品","会社","場所"]);
    case 19:return `<div class="dependency">${box("A 候補キー")}${arrow() + box("B 非キー")}${arrow("推移的従属") + box("D 非キー","danger")}<strong>第3正規形を満たさない</strong></div>`;
    case 20:return `<div class="union"><div><b>表R</b><span>列1</span><span>列2</span></div><i>UNION</i><div><b>表S</b><span>列1</span><span>列2</span></div><strong>列数・対応する型をそろえる</strong></div>`;
    case 21:return flow(["アプリから CALL","DBサーバ内の手続","複数SQLをまとめて実行"]);
    case 22:return cycle(["トランザクション停止","バッファをDBへ書出し","チェックポイントをログ記録","再開"]);
    case 23:return `<div class="peer"><span>💻 PC</span><b>Wi‑Fi Direct<br><small>AP不要</small></b><span>🖨️ プリンタ</span></div>`;
    case 24:return stack(["7 アプリケーション","6 プレゼンテーション","5 セッション","4 トランスポート","3 ネットワーク","2 データリンク","1 物理"]);
    case 25:return `<div class="packet"><span>プロトコル</span><span>送信元IP</span><span>宛先IP</span><span>送信元Port</span><span class="hot">宛先Port<br><b>サービス識別</b></span></div>`;
    case 26:return `<div class="snmp">${box("SNMP Manager")}${arrow("GET / SET")} ${box("Agent / MIB","focus")}<div class="return">← TRAP（障害通知）</div></div>`;
    case 27:return stack(["通常の画面・コマンド","OSの表示やログ","ルートキットが改変・隠蔽","侵入者のプロセス／ファイル"]);
    case 28:return `<div class="broken"><span>安全性<br><small>衝突発見は非現実的</small></span><b>⚡ 新しい攻撃法</b><span class="danger">危殆化<br><small>現実的時間で衝突</small></span></div>`;
    case 29:return `<div class="seesaw"><span>本人拒否率<br><b>FRR</b></span><i></i><span>他人受入率<br><b>FAR</b></span><strong>しきい値でトレードオフ</strong></div>`;
    case 30:return flow(["ランダム・境界・不正入力","中身を見ずに大量投入","停止・異常・脆弱性を検知"]);
    case 31:return cycle(["端末の挙動を記録","不審な動きを検知","管理者へ通知・調査","隔離・プロセス停止"]);
    case 32:return `<div class="gate"><div>社内</div><div>社外</div><b>どちらも毎回検証</b><span>利用者</span><span>端末状態</span><span>状況</span><em>最小権限で許可</em></div>`;
    case 33:return `<div class="escape"><code>&lt;script&gt;攻撃&lt;/script&gt;</code><b>出力エスケープ</b><code>&amp;lt;script&amp;gt;</code><span>タグではなく文字として表示</span></div>`;
    case 34:return `<div class="dfd-legend"><div><span class="dfd-external">顧客</span><small>外部実体</small></div><div><span class="dfd-process">受注処理</span><small>プロセス</small></div><div><span class="dfd-store">商品マスタ</span><small>データストア</small></div><div><span class="dfd-flow">受注伝票 →</span><small>データフロー</small></div><strong>「何をするか」より「データがどう流れるか」を読む</strong></div>`;
    case 35:return `<div class="inherit">${box("基底クラス<br><small>共通データ・機能</small>")}${arrow("継承")}<div>${box("サブクラスA<br>差分だけ追加","focus")}${box("サブクラスB<br>一部を上書き","focus")}</div></div>`;
    case 36:return `<div class="services"><div>会員</div><div>注文</div><div>決済</div><div>配送</div><span>独立配備</span><span>API連携</span></div>`;
    case 37:return `<div class="classes"><div class="bad">無効<br>〜0</div><div class="good">有効<br>1〜100<br><b>代表値 50</b></div><div class="bad">無効<br>101〜</div></div>`;
    case 38:return `<div class="components"><span>検索部品</span><span>認証部品</span><span>決済部品</span><b>公開インタフェースで組立</b></div>`;
    case 39:return `<div class="backlog"><span><b>1</b>価値が高い機能</span><span><b>2</b>次に重要な機能</span><span><b>3</b>将来の候補</span><em>Product Owner が順序付け</em></div>`;
    case 40:return cycle(["RED：失敗するテスト","GREEN：最小実装で成功","REFACTOR：動作を保って改善"]);
    case 41:return `<div class="baseline"><span>スコープ</span><span>スケジュール</span><span>コスト</span><b>計画でベースライン確定</b><div>実績を測る物差し</div></div>`;
    case 42:return `<div class="critical-path"><div class="cp-row"><span>経路1</span><i style="--w:100%"></i><b>最長</b></div><div class="cp-row"><span>経路2</span><i style="--w:88%"></i></div><div class="cp-action">① 最長経路上を1日短縮</div><div class="cp-row after"><span>再計算</span><i style="--w:93%"></i><i style="--w:93%"></i><b>2本とも最長</b></div><div class="cp-action">② 両方に効く作業、または各経路の作業を短縮</div></div>`;
    case 43:return `<div class="matrix"><b>緊急度 ↑</b><div>中</div><div class="hot">最優先</div><div>低</div><div>高</div><span>影響度 →</span></div>`;
    case 44:return `<div class="availability"><div><span>DB</span><b>0.99</b></div><em>×</em><div><span>Web</span><b>0.93</b></div><em>×</em><div><span>NW</span><b>0.97</b></div><strong>＝ 約0.893 → 89%</strong><small>直列構成：全部が稼働する確率を掛ける</small></div>`;
    case 45:return compare("独立性を損なう",["規程を作る","設計・運用する"],"独立性を保つ",["導入前にレビュー","評価・助言する"]);
    case 46:return cycle(["計画：設計","実行：割当・記録","検証：実績分析","改善：業務見直し"]);
    case 47:return `<div class="venn"><span>既存産業</span><span>先端IT</span><b>X‑Tech<br><small>新しい価値</small></b></div>`;
    case 48:return `<div class="bsc"><div>財務<br><small>利益率</small></div><div>顧客<br><small>満足・苦情</small></div><div class="hot">内部プロセス<br><small>受注→出荷日数</small></div><div>学習と成長<br><small>研修・能力</small></div></div>`;
    case 49:return `<div class="ppm"><b class="axis-y">市場成長率 ↑</b><div class="star">花形<br><small>高成長・高シェア</small></div><div class="question">問題児<br><small>高成長・低シェア<br><em>投資で育成</em></small></div><div class="cash">金のなる木<br><small>低成長・高シェア</small></div><div class="dog">負け犬<br><small>低成長・低シェア</small></div><b class="axis-x">市場占有率　高 ← → 低</b></div>`;
    case 50:return `<div class="cannibal"><div>自社の紙媒体</div><i>顧客が移動</i><div>自社の電子版</div><b>自社商品同士で売上を奪い合う</b></div>`;
    case 51:return `<div class="bmc"><div>主要パートナー</div><div>主要活動<br><small>主要資源</small></div><div class="value">価値提案</div><div>顧客との関係<br><small>チャネル</small></div><div>顧客セグメント</div><div class="wide">コスト構造</div><div class="wide revenue">収益の流れ</div><strong>左：価値を作る仕組み　中央：届ける価値　右：顧客</strong></div>`;
    case 52:return cycle(["課題・アイデア","チームで短期開発","プロトタイプ","デモ・発表"]);
    case 53:return `<div class="rpa"><div><span>人</span><p>定型手順を設計</p></div><b>RPA Bot</b><div><span>PC業務</span><p>入力・転記・照合・メール</p></div></div>`;
    case 54:return `<div class="harvest"><span>☀ 光</span><span>♨ 熱</span><span>〰 振動</span><b>変換・蓄電</b><em>IoTセンサへ給電</em></div>`;
    case 55:return network("投稿",["フォロワー","友人","コミュニティ","再共有"]);
    case 56:return compare("Off-JT",["講習会","通信教育・研修"],"OJT",["実際の職場","指導者と業務"]);
    case 57:return `<div class="moving-average"><div class="ma-window"><span>3か月</span><i style="--w:48%"></i><b>平均 → 誤差</b></div><div class="ma-window"><span>4か月</span><i style="--w:62%"></i><b>平均 → 誤差</b></div><div class="ma-window"><span>5か月</span><i style="--w:77%"></i><b>平均 → 誤差</b></div><div class="ma-window best"><span>6か月</span><i style="--w:92%"></i><b>実績203との差が最小</b></div><small>窓幅ごとに平均し、|予測値−実績値|を比較</small></div>`;
    case 58:return `<div class="pareto"><div class="bars"><i style="--h:90%"></i><i style="--h:62%"></i><i style="--h:40%"></i><i style="--h:22%"></i><i style="--h:12%"></i></div><svg viewBox="0 0 300 160"><polyline points="20,115 78,70 136,40 194,22 252,12 290,8"/></svg><span>件数：大きい順の棒</span><b>累積割合：右上がりで100%へ</b></div>`;
    case 59:return stack(["売上高","− 売上原価","＝ 売上総利益","− 販管費","＝ 営業利益","± 営業外損益","＝ 経常利益","− 特別損失（固定資産売却損）"]);
    case 60:return flow(["利用目的を明示","本人がDM送付「可」","同意した目的で利用"]);
    default:return flow(q.diagram);
  }
}
window.renderRichVisual=richVisual;
